# Setup
title:               classified5
tagline:             'Blog'
description:         'A simple blog about things I want to share. Theme Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>. <a href="https://github.com/poole/lanyon" target="_blank">Theme Repo</a>'
url:                 https://classified5.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Aditya Ikhsan
  url:               https://classified5.github.io
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
