# Setup
title:               classified5
tagline:             'Blog'
description:         'A simple blog about things I want to share. Enjoy!'
url:                 https://classified5.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Aditya Ikhsan
  url:               https://classified5.github.io
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
