# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            classified5
tagline:          'Blog'
description:      'Hyde - Theme Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://classified5.github.io/
baseurl:          ''

author:
  name:           'Aditya Ikhsan'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
